### ISSUE TITLE
Windows下0.92无法自动新建文件夹

### ISSUE THREAD

**Issue by WindnBike** [mushanshitiancai/vscode-paste-image#11]
您好，
今天升级了新版本，不过无法自动新建文件夹了。
我设置的参数是：
"pasteImage.path": "${currentFileDir}/images/"
其他参数不变。
如果没有images文件夹时，会警告说Running the contributed command:'extension.pasteImage' failed.
如果存在images文件夹时，顺利粘贴。
这次的更新非常棒，期待下一个版本~

**Comment by mushanshitiancai** [comment]
我更新插件了，修复了该问题。还有什么问题欢迎反馈
