### ISSUE TITLE
Unable to paste images on win10

### ISSUE THREAD

**Issue by ELBe7ery** [mushanshitiancai/vscode-paste-image#12]
In settings i am setting the path property to `"pasteImage.path": "${currentFileDir}\\assets"`
However when i enter the paste command, the "assets" folder is created but the image is not.

![image](https://media.giphy.com/media/3og0IzrZWyGPQyAjqE/giphy.gif)
[GIF link](https://giphy.com/gifs/3og0IzrZWyGPQyAjqE/fullscreen)

**Comment by mushanshitiancai** [comment]
Hello, I try it in my windows 10, and it's ok

![](https://media.giphy.com/media/l0IyoQV6BOxqilzoI/giphy.gif)

**Comment by mushanshitiancai** [comment]
You can do a test. First save this powershell script to a file named "ps.pc1":

```
param($imagePath)

# Adapted from https://github.com/octan3/img-clipboard-dump/blob/master/dump-clipboard-png.ps1

Add-Type -Assembly PresentationCore
$img = [Windows.Clipboard]::GetImage()

if ($img -eq $null) {
    "no image"
    Exit 1
}

if (-not $imagePath) {
    "no image"
    Exit 1
}

$fcb = new-object Windows.Media.Imaging.FormatConvertedBitmap($img, [Windows.Media.PixelFormats]::Rgb24, $null, 0)
$stream = [IO.File]::Open($imagePath, "OpenOrCreate")
$encoder = New-Object Windows.Media.Imaging.PngBitmapEncoder
$encoder.Frames.Add([Windows.Media.Imaging.BitmapFrame]::Create($fcb)) | out-null
$encoder.Save($stream) | out-null
$stream.Dispose() | out-null

$imagePath
```

And then you copy a image, open a powershell window, run this script: `powershell -f ps.pc1 "D:\\test.png"`, observe the output.

**Comment by ELBe7ery** [comment]
![image](https://user-images.githubusercontent.com/11269928/27924748-32d8573e-6237-11e7-9652-3fa8bea81495.png)

After selecting "open with Paint" it keep showing this.

I will try on my other windows 10 device maybe this is a problem related to my system.

**Comment by ELBe7ery** [comment]
![image](https://user-images.githubusercontent.com/11269928/27935919-e9167438-6262-11e7-85ad-09fd91df8048.png)

It just prints out the argument given.

**Comment by ELBe7ery** [comment]
I have found the issue; 

![image](https://user-images.githubusercontent.com/11269928/27938100-a7d3c7c4-6270-11e7-8cc9-0f984638cbce.png)

It turns out that if  `powershell` is not added into the system environmental variables the code required for paste will throw an exception since it is not able to launch the powershell script 

![image](https://user-images.githubusercontent.com/11269928/27938217-66185506-6271-11e7-8bb4-f788db5413ce.png)

I am doing a pull request to fix this issue. Adding the full powerscript path into the variable powershell should fix this problem in case users dont have powershell.exe added to system env. vars

![image](https://user-images.githubusercontent.com/11269928/27938311-05bdd086-6272-11e7-84cb-4a8cf24d82a0.png)

**Comment by mushanshitiancai** [comment]
Very very thank you for you experiment!

I update plugin, fix this bug and enhance the log system. You can try it.
