### ISSUE TITLE
windows下好像不管用

### ISSUE THREAD

**Issue by visonforcoding** [mushanshitiancai/vscode-paste-image#14]
老哥能否开发支持下上传到七牛或者自己服务器图床，在粘贴图片的时候。并且我试了本地的粘贴也不管用。

**Comment by mushanshitiancai** [comment]
看一下日志输出：

![image](https://user-images.githubusercontent.com/4251771/28563313-34f5218e-7158-11e7-8cc4-15a9db5e3c27.png)

目前没有兴趣开发这个功能，你可以在目前的基础上扩展，然后提Merge Request，我合并进来。

**Comment by visonforcoding** [comment]
ctrl+alt+v 没任何反应，也没有日志输出。

**Comment by visonforcoding** [comment]
可以了。突然一下蹦出来了！多谢~ 好的。
