### ISSUE TITLE
Paste images from the web links

### ISSUE THREAD

**Issue by finalion** [mushanshitiancai/vscode-paste-image#15]
This extension frees me a lot of tedious work, thanks.  
Commonly, I have some requirements copying web images, and I know I can make a capture and paste it using this extension. But sometimes I want to grab the orignal image. Is this feature possible to be considered in your development?

**Comment by mushanshitiancai** [comment]
Hello，you can copy image  to clipboard(instand of capture) and then use paste-image.

**Comment by finalion** [comment]
Yes, it works! I thought it only supports capture. Thanks.
