### ISSUE TITLE
Get wrong result when copy file directly from finder and paste in vscode

### ISSUE THREAD

**Issue by moddyan** [mushanshitiancai/vscode-paste-image#16]
After copy a jpg file (press cmd+c when focus the file in finder) and paste in vs code,  I got the below image.

![qq20170829-201545](https://user-images.githubusercontent.com/4135395/29820388-df1fd0dc-8cf6-11e7-920d-0e576ebb83d5.png)

when the original image attached below
![b4adbe3eb661d32d1bf83ac692e5e48b_b](https://user-images.githubusercontent.com/4135395/29820423-00e6a0ce-8cf7-11e7-950e-634e7675c5d7.jpg)

**Comment by mushanshitiancai** [comment]
你的原图很有意思😊

这个是finder的行为。在finder中选中文件按ctrl+c，finder会把文件的logo图片复制到剪贴板。你可以在其他软件中粘贴，会发现也是一样的结果。

我的解决办法是打开文件后在复制。不知道是否还有更好的方法。
