### ISSUE TITLE
pasteImage.path里面的变量不起作用

### ISSUE THREAD

**Issue by dptr** [mushanshitiancai/vscode-paste-image#17]
配置如下：
"pasteImage.path": "assets/${currentFileNameWithoutExt}",
但是当粘贴图片的时候，提示
![image](https://user-images.githubusercontent.com/3236685/30096889-627c360c-930d-11e7-892d-030bb4219976.png)
保存最后生成的文件夹中，这个变量也没有被替换

**Comment by dptr** [comment]
哦这个我搞错了，跟markdown paste image弄混了，两个插件功能类似，名字也类似。

**Comment by mushanshitiancai** [comment]
看了下，这个markdown paste image是fork我的项目。我这边更新的变量的功能他没有同步过去
