### ISSUE TITLE
How to change the filname including currentFileNameWithoutExt

### ISSUE THREAD

**Issue by tatoosh** [mushanshitiancai/vscode-paste-image#20]
First i want to thank you for your plugin!

My config is this:
```"pasteImage.path":"${currentFileDir}/assets/${currentFileNameWithoutExt}"```

so my result imagename is:
```![](assets/Bestellprozesse/2018-01-23-13-46-54.png)```

How to change the Filename to this ?
```![](assets/Bestellprozesse_2018-01-23-13-46-54.png)```

**Comment by tatoosh** [comment]
Is this project closed ?

**Comment by stvhwrd** [comment]
Paging @mushanshitiancai

**Comment by mushanshitiancai** [comment]
Hi, I'm come back😄

You can update vscode-paste-image to v1.0.1. 

New configuration `pasteImage.namePrefix` can meet your need. Like this:

```
"pasteImage.path":"${currentFileDir}/assets"
"pasteImage.namePrefix": "${currentFileNameWithoutExt}_",
```

**Comment by mushanshitiancai** [comment]
@tatoosh Sorry, It's a bug. I fixed in version 1.0.2.

**Comment by tatoosh** [comment]
thx @mushanshitiancai, it's working now. now the image got the base filename and a timestamp.
Any change to open a popup who is asking for the image filename?

**Comment by mushanshitiancai** [comment]
@tatoosh You can select text as the file name (see the gif on home page).
