### ISSUE TITLE
Azure Blob Storage support

### ISSUE THREAD

**Issue by devlead** [mushanshitiancai/vscode-paste-image#23]
We often try to keep binaries out of GIT repositories, it would be nice if it was possible on paste to upload image to Azure Blob Storage and get blob absolute url to uploaded file as markdown.

**Comment by mushanshitiancai** [comment]
Hello, I got your point. And I think many people have the same needs.

But there are so many third part storage service, it's hard to implement all of them to cover everyone needs.

If you are interest in this project, you can fork and add Azure Blob Storage support, Let's make this extension better!
