### ISSUE TITLE
to edit a folder containing the images?

### ISSUE THREAD

**Issue by mshrn** [mushanshitiancai/vscode-paste-image#26]
Is it impossible to save the pasted images on a file in a folder whose name is same as the file's name?
I tried `"pasteImage.basePath": "${currentFileDir}/${fileBasenameNoExtension}"`, but it did not work.

**Comment by mushanshitiancai** [comment]
Hello, you can try: `"pasteImage.path": "${currentFileDir}/${currentFileNameWithoutExt}"`

**Comment by mshrn** [comment]
Thanks a lot.
