### ISSUE TITLE
How to setup on Linux?

### ISSUE THREAD

**Issue by Philiphlop** [mushanshitiancai/vscode-paste-image#27]
Hello, I'm unable to get this working on Fedora Core 28. I have installed xclip from the default repo, but still get the error of 

> You need to install xclip command first. 

The same result happens regardless of how I paste it

1. Take screenshot, copy that to clipboard, attempt to paste
2. Take screenshot, save to file, copy file, attempt to paste

```
$ uname -a
Linux desktop 4.16.13-300.fc28.x86_64 #1 SMP Wed May 30 14:31:00 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ 
$ xclip -version
xclip version 0.13
Copyright (C) 2001-2008 Kim Saunders et al.
Distributed under the terms of the GNU GPL
$ 
```

I tested xclip and it works fine within the terminal

```
$ uptime | xclip
$ 
$  19:42:01 up 8 min,  2 users,  load average: 0.42, 0.49, 0.29
bash: 19:42:01: command not found...
$ 
$ echo "test" | xclip
$ test
```

Am I missing something, do I need to add an extra step?

**Comment by tedour** [comment]
Hi !
Same error here on Manjaro...
~ >>> command -v xclip                                                         
/usr/bin/xclip
~ >>> echo $?                                                                  
0

Thank you for help !

**Comment by jrherrick** [comment]
Greetings Linux folks. Perhaps like me, you arrived here holding this delightful extension in contempt. Perhaps like me, vscode isn't a toolchain mainstay and you weren't mindful of the fact that you're running vscode from within a container, isolated from xclip. You may want check if this is the case by running the above recommended verification commands from within the vscode terminal. This simple act lit a candle in my moment of darkness.

Don't get me wrong, I don't yet know what to do. I mean... it IS just a candle and the moment continues. However, I can now say that the darkness is less of an encumberance.

Take Care,
An I-love-the-vscode-markdown-flow-with-Mushan's-extension vim user

In a non-sandboxed terminal:

> toor@seclab:~ xclip -version
> xclip version 0.13
> toor@seclab:~ hostname
> seclab


Inside this bubble-wrapped vscode terminal:

> sh-5.2 xclip -version
> sh: xclip: command not found
> sh-5.2 hostname
> seclab

Thanks Mushan!
