### ISSUE TITLE
Can we paste image in a subfolder?

### ISSUE THREAD

**Issue by soloman817** [mushanshitiancai/vscode-paste-image#3]
This is exactly what I'm looking for!!

Currently it paste image in the same folder, would it be possible to create a subfolder, like images then put all images under that folder?

**Comment by mushanshitiancai** [comment]
I understand what u mean, but it's hard to design a unified interaction

**Comment by soloman817** [comment]
Is it possible to use a configuration?

**Comment by mushanshitiancai** [comment]
@soloman817 hello, now vscode-paste-image support config folder to save image. You can update and try it.
