### ISSUE TITLE
Default Ctrl+Alt shortcuts interfere with normal OS operation

### ISSUE THREAD

**Issue by Vrlwrox** [mushanshitiancai/vscode-paste-image#30]
Please don't use Ctrl+Alt shortcuts as default shortcuts. They interfere with normal operation when working with international keyboards. The Ctrl+Alt combination is mapped to AltGr key which enables user to enter alternative characters. For example, on my keyboard, AltGr+V should enter "@". Instead, it triggers this extension.

**Comment by mushanshitiancai** [comment]
Hello, you can change the default key binding:

![image](https://user-images.githubusercontent.com/4251771/47721768-cb0d2000-dc8b-11e8-9327-7298f4599a2f.png)
