### ISSUE TITLE
Allow "pasting" when clipboard contains path to local file with an image

### ISSUE THREAD

**Issue by ivan-danilov** [mushanshitiancai/vscode-paste-image#35]
Would be a convenient addition.

**Comment by mushanshitiancai** [comment]
Hello, I think it's a low frequency use case. You can open file and copy to clipboard and then paste.

**Comment by ivan-danilov** [comment]
Not always convenient: if the file is prepared jpeg with some specifically chosen quality value, and pasting content seems to always create PNG. Huge one.

**Comment by azu** [comment]
I think that A lot of note app support this usecase.

- Quiver
- DayOne
- Notion
- OneNote
- EverNote
- macOS's Notes.app
- etc..

**Comment by mushanshitiancai** [comment]
@azu How to paste image to macOS's Notes.app when a image path in clipboard?
