### ISSUE TITLE
Setting failed

### ISSUE THREAD

**Issue by VonSdite** [mushanshitiancai/vscode-paste-image#36]
## I hope the Paste Image plugin can support setting up a configuration for a single project

In `vscode` **version 1.29**, 
- I open **multiple documents** in vscode, and I want to set the configuration of **a single project**, but vscode **does not support it**, as shown in the figure.

![image](https://user-images.githubusercontent.com/25704948/48596121-83c4a600-e992-11e8-9dee-8d9f0b1dbffc.png)

- and i found it in vscode's document, https://code.visualstudio.com/docs/editor/multi-root-workspaces

![image](https://user-images.githubusercontent.com/25704948/48597746-3f3d0880-e99a-11e8-83cb-a04ade70eb85.png)

**Comment by mushanshitiancai** [comment]
It seems a new feture to vscode. I would add support in next release.
