### ISSUE TITLE
Would be nice to have a feature to automatically set alt text to the file name

### ISSUE THREAD

**Issue by raboley** [mushanshitiancai/vscode-paste-image#42]
Hi love this extensions! Maybe I'm not using the settings correctly, but when I highlight a word then paste in the image it pastes in like this:

```
![](Repo_Layout.png)
```

but it would be really nice if the alt text could automatically be updated with the file name or path when pasting it in.

```
![Repo_Layout.png](Repo_Layout.png)
```

Thank you again for your hard work I love this extension makes documentation so much easier!

**Comment by yuyujulin** [comment]
+1， and it's better that  don't include the extention name and the path into the alt text.  File name is enough, like this ![Repo_Layout](assets/Repo_Layout.png)

**Comment by gojanpaolo** [comment]
+1 on this feature. I'd also prefer just the file name without the extension as the default. 
A setting similar to `insertPattern` is nice to have as well so we can do other things like include extension.

**Comment by mushanshitiancai** [comment]
Hello, you can set `insertPattern` to `![${imageFileName}](${imageFilePath})` or `![${imageFileNameWithoutExt}](${imageFilePath})`

![image](https://user-images.githubusercontent.com/4251771/60395154-d5a4ef80-9b61-11e9-963d-7449b691ceb5.png)

**Comment by gandalfsaxe** [comment]
@mushanshitiancai Great! I think you should mention this as an example in insertPattern and explicitely mention the word "alternative text" and "alt text" so it's obviously as a use case :) I'll make a PR.

**Comment by gandalfsaxe** [comment]
Ah never mind, it's already in the README.md on the repo, but not pushed to the VSCode Marketplace yet. I'll open an issue on that instead.
