### ISSUE TITLE
Paste image wrong ?

### ISSUE THREAD

**Issue by MamoruMachida** [mushanshitiancai/vscode-paste-image#46]
When paste image, every image looks like an attached image

optional settings
``` json
    "pasteImage.namePrefix": "${currentFileNameWithoutExt}_",
    "pasteImage.prefix": "/",
    "pasteImage.path": "${projectRoot}/img",
    "pasteImage.basePath": "${projectRoot}",
```

![image](https://user-images.githubusercontent.com/30787346/59275393-32b23180-8c97-11e9-80f8-f37df61ca354.png)

**Comment by mushanshitiancai** [comment]
On the Finder of MacOS, copy a image file would only copy the icon of file, you have to open file and then copy image.

**Comment by MamoruMachida** [comment]
thanks
