### ISSUE TITLE
无法正常工作

### ISSUE THREAD

**Issue by haccanri** [mushanshitiancai/vscode-paste-image#7]
我很喜欢这个功能，但我下载这个插件后无法正常使用。通过Ctrl+Shift+P输入paste image命令或者Ctrl+Alt+V都没有任何反应，确认剪切板中有图片。

我最近才开始用VS code，是1.10.2，目前的最新版本，是不是VS Code升级导致这个插件失效了？希望作者能fix下。

**Comment by haccanri** [comment]
Problem solved. Should add powershell to system path since the implementation on Windows depends on powershell. I suggest adding it to the instructions.

**Comment by fghhfg** [comment]
@haccanri `add powershell to system path` How to do it?

**Comment by haccanri** [comment]
@fghhfg , first search "powershell" in start menu and find its location. My location of powershell is `%SystemRoot%\system32\WindowsPowerShell\v1.0\powershell.exe`. Then add `%SystemRoot%\system32\WindowsPowerShell\v1.0\` to the system variable `Path` to make sure the extension can call it through command line. Here is how to set system variable, <https://superuser.com/questions/284342/what-are-path-and-other-environment-variables-and-how-can-i-set-or-use-them>. After setting the path, you can type powershell in the command line window to varify whether it works and then test this extension. It works for me.
