### ISSUE TITLE
Windows "/" issue

### ISSUE THREAD

**Issue by GitJit** [mushanshitiancai/vscode-paste-image#8]
I am in Windows, I created a new relative path as following..

`  "pasteImage.path": "./images"`

But when I paste image it seems like "\" is placed instead of "/" and Git hub is not rendering the image.
I think it should be

`![](images\2017-03-22-09-27-53.png)`

instead of 

`![](images/2017-03-22-09-27-53.png)`

Let me know If I am missing some thing...

**Comment by haccanri** [comment]
I also have this problem

**Comment by mushanshitiancai** [comment]
Hello, I just update plugin. Now have a new `pasteImage.forceUnixStyleSeparator` config. And it default set to true.
