### ISSUE TITLE
Fallback to regular paste when no image in clipboard

### ISSUE THREAD

**Issue by riccardoferretti** [mushanshitiancai/vscode-paste-image#87]
Hi, I really like the extension, thanks for your work.
The only thing I found less intuitive was the different keyboard shortcut, `cmd+alt+v`

I was curious to map the command to `cmd+v`, but couldn't do it because when there is text and not an image in the clipboard, instead of pasting I get a notification.

Would it be possible to have Paste Image:
- do the pasting if there is an image in the clipboard
- fallback to the regular pasting command in case there is something else

This way we wouldn't need to remember a second key-combo, wdyt?

**Comment by hmalphettes** [comment]
@riccardoferretti, also a fan of the extension and so are my colleagues.

Great idea and I think it is possible.

If that is helpful, you can get a good idea of where the external script in charge of findin data in the Clipboard and how it communicates with the javascript side of the plugin by staring at my pull request: 
https://github.com/mushanshitiancai/vscode-paste-image/pull/85/files

So on windows for example the current powershell returns:

```powershell
$img = [Windows.Clipboard]::GetImage()
if ($img -eq $null) {
    "no image"
    Exit 1
}
```

We would need to tweak this so we know when to fall back to the standard Paste.
We would need to do the same for each OS and their own external script.

**Comment by riccardoferretti** [comment]
hey @hmalphettes, I was wondering if you could use the vscode `editor.action.clipboardPasteAction` command instead and have it deal with the OS specific implementation, wdyt?

**Comment by vezaynk** [comment]
Hi @riccardoferretti 

This repository has not seen any activity in over 3 years. There is an actively maintained fork here: https://github.com/telesoho/vscode-markdown-paste-image

With that said, I considered implementing the feature you are asking for and decided against it for the following reasons:

- The way the pasting works here is slow (up to a couple seconds in some cases). The snappiness of the app would be hurt significantly if all pastes were to go through this process.
- It may also cause an HTML paste when you wanted a plain text paste or vice-versa causing more issues than it solves.

I recommend treating ctrl+v as simple paste and ctrl+alt+v as rich paste.

**Comment by riccardoferretti** [comment]
Thanks for the reply @knyzorg - you are bringing up good points
