### ISSUE TITLE
Add an option to set up alt text

### ISSUE THREAD

**Issue by natakazakova** [mushanshitiancai/vscode-paste-image#98]
Hi. I need a capability to specify **alt text** for the image.

```
 ![alt text](image URL)
```

Alt text helps people with visual impairments understand pictures and other graphical content when they use a screen reader. And Google [recommends](https://developers.google.com/search/docs/beginner/how-search-works) to use annotations for images and video.

As I found in the extension settings, I can configure only the `image URL` part. I use the human-readable image names and what I need is a template to insert the image name to alt text: `![human-readable-image-name](some-path/human-readable-image-name.png)`. Is it possible?

**Comment by Chaphasilor** [comment]
It works if you set `pasteImage.insertPattern` to `![${imageFileNameWithoutExt}](${imageFilePath}${imageSyntaxSuffix}`!  
It's a bit of a workaround, and you need to first type the alt text, then select it, and then paste the image...

Keep in mind that the image name will be the escaped alt text.

Here's a quick demo:   
https://user-images.githubusercontent.com/18015147/138860998-b5aa791d-7c16-45de-b97e-7599c7c1c841.mp4

**Comment by natakazakova** [comment]
@Chaphasilor wow, great! This is exactly what I need. Thanks a lot. This workaround works great.
